[project]
name = "iu-era5-grabber"
version = "0.1.0"
description = "Synchronizes NCAR RDA ERA5 files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "globus-cli>3",
    "pandas>=2.3.1",
]
